# local profile must be manually created after
# pulling the credentials from the bucket secret
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: backup-bucket
spec:
  bucketName: kasten-k10-backups
  storageClassName: rook-ceph-bucket
