apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 11.1.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    fullnameOverride: postgresql
    postgresqlPassword: ${AUTHENTIK_POSTGRESQL_PASSWORD}
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 14.2.0
      pullPolicy: IfNotPresent
    persistence:
      enabled: true
