apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zro-wildcard-certificate
  namespace: istio-system
spec:
  secretName: zro-wildcard-certificate
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
    - ${ORGANIZATION_NAME}
  commonName: ${CLUSTER_DOMAIN}
  dnsNames:
  - "${CLUSTER_DOMAIN}"
  - "*.${CLUSTER_DOMAIN}"
  - "${KNATIVE_DOMAIN}"
  - "*.${KNATIVE_DOMAIN}"
  - "*.api.${KNATIVE_DOMAIN}"
  - "*.tekton-pipelines.${KNATIVE_DOMAIN}"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
