# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args: [ --unsafe ]
  - id: check-added-large-files
    args: [ --maxkb=2048 ]
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.10
  hooks:
  - id: forbid-crlf
  - id: forbid-tabs
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.5
  hooks:
  - id: shellcheck
    args: [ --severity=error ]
- repo: https://github.com/adrienverge/yamllint
  rev: v1.26.2
  hooks:
  - id: yamllint
- repo: https://github.com/k8s-at-home/sops-pre-commit
  rev: v2.0.3
  hooks:
  - id: forbid-secrets
