# https://taskfile.dev
---
version: "3"

tasks:
  default:
    cmds:
    - go-task -l
    silent: true

  upgrade:flux:
    desc: upgrade flux component manifest
    cmds:
    - flux install --export > cluster/base/flux-system/gotk-components.yaml
  upgrade:flux-cli:
    desc: upgrade local flux command line binary
    cmds:
    - ./bin/update.sh flux
