---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-tekton
resources:
- https://github.com/tektoncd/pipeline/releases/download/v0.24.1/release.yaml
- https://github.com/tektoncd/dashboard/releases/download/v0.17.0/tekton-dashboard-release.yaml
