apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: memcached
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://charts.bitnami.com/bitnami
      chart: memcached
      version: 5.15.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    image:
      registry: docker.io
      repository: bitnami/memcached
      tag: 1.6.12
      pullPolicy: IfNotPresent
