apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://dl.gitea.io/charts/
      chart: gitea
      version: 4.0.3
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
  values:
    image:
      repository: gitea/gitea
      tag: 1.14.6
      pullPolicy: IfNotPresent
    persistence:
      enabled: true
      existingClaim: gitea-data
    statefulset:
      labels:
        sidecar.istio.io/inject: "true"
    gitea:
      database:
        builtIn:
          postgresql:
            enabled: false
      cache:
        builtIn:
          enabled: false
      config:
        default:
          APP_NAME: Zro
          BRANCH: main
        server:
          DISABLE_SSH: true
        database:
          DB_TYPE: postgres
          HOST: postgresql.gitea.svc:5432
          NAME: postgres
          USER: postgres
          PASSWD: ${GITEA_POSTGRESQL_PASSWORD}
        cache:
          ADAPTER: memcache
          ENABLED: true
          HOST: memcached:11211
