# this is for migrating data from one pvc to another
# replace the namespace, and volumes
apiVersion: batch/v1
kind: Job
metadata:
  namespace: ${NS}
  name: migrate-${OLDVOL}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      name: migrate-${OLDVOL}
      labels:
        name: volume-migration
        old-volume: ${OLDVOL}
        new-volume: ${NEWVOL}
    spec:
      restartPolicy: Never
      containers:
      - name: volume-migration
        image: ubuntu:xenial
        tty: true
        command: [ "/bin/sh" ]
        args: [ "-c", "cp -r -v /mnt/old/ /mnt/new/" ]
        volumeMounts:
        - name: old-vol
          mountPath: /mnt/old
        - name: new-vol
          mountPath: /mnt/new
      volumes:
      - name: old-vol
        persistentVolumeClaim:
          claimName: ${OLDVOL} # change to data source PVC
      - name: new-vol
        persistentVolumeClaim:
          claimName: ${NEWVOL} # change to data target PVC
