apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-tls
spec:
  secretName: unifi-tls
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
    - ${CERTIFICATE_ORG_NAME}
  commonName: unifi.${CLUSTER_DOMAIN}
  dnsNames:
  - "unifi.${CLUSTER_DOMAIN}"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
