apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: unifi
spec:
  frequency: '@daily'
  retention:
    daily: 7
    monthly: 12
    weekly: 4
    yearly: 7

  selector:
    matchExpressions:
    - key: k10.kasten.io/appNamespace
      operator: In
      values:
      - unifi

  actions:
  - action: backup
    backupParameters:
      filters:
        includeResources:
        - resource: persistentvolumeclaims
  - action: export
    exportParameters:
      frequency: '@daily'
      exportData:
        enabled: true
      migrationToken:
        name: unifi-migration-token-jjdm8
        namespace: system-kasten
      profile:
        name: ceph
        namespace: system-kasten
    retention: {}
