apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubedb-crds
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://charts.appscode.com/stable/
      chart: kubedb-crds
      version: v2021.04.16
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: flux-system
  values: {}
