apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-env
data:
  HASS_DATABASE_URL: "${HASS_DATABASE_DATASOURCE}"
  HASS_HOME_LATITUDE: "${HASS_HOME_LATITUDE}"
  HASS_HOME_LONGITUDE: "${HASS_HOME_LONGITUDE}"
  HASS_HOME_ELEVATION: "${HASS_HOME_ELEVATION}"
  HASS_BLINK_USERNAME: "${HASS_BLINK_USERNAME}"
  HASS_BLINK_PASSWORD: "${HASS_BLINK_PASSWORD}"
  HASS_CLIMATE_PLATFORM: "${HASS_CLIMATE_PLATFORM}"
  HASS_CLIMATE_USERNAME: "${HASS_CLIMATE_USERNAME}"
  HASS_CLIMATE_PASSWORD: "${HASS_CLIMATE_PASSWORD}"
  HASS_MQTT_USERNAME: "${HASS_MQTT_USERNAME}"
  HASS_MQTT_PASSWORD: "${HASS_MQTT_PASSWORD}"
  HASS_MYQ_USERNAME: "${HASS_MYQ_USERNAME}"
  HASS_MYQ_PASSWORD: "${HASS_MYQ_PASSWORD}"
  HASS_NWS_APIKEY: "${USER_EMAIL}"
