apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 9.20.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    image:
      name: traefik
      tag: 2.4.8
      pullPolicy: IfNotPresent
    deployment:
      enabled: true
      replicas: 2
    logs:
      access:
        enabled: true
