apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics-agent
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://victoriametrics.github.io/helm-charts/
      chart: victoria-metrics-agent
      version: 0.7.19
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
  values:
    image:
      repository: victoriametrics/vmagent
      tag: v1.61.1
      pullPolicy: IfNotPresent
