apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: agent
spec:
  image:
    repository: victoriametrics/vmagent
    tag: v1.61.1
    pullPolicy: IfNotPresent

  remoteWrite:
  - url: http://vmsingle-store:8429/api/v1/write

  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 2Gi
