apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: agent
spec:
  image:
    repository: victoriametrics/vmagent
    tag: v1.61.1
    pullPolicy: IfNotPresent

  remoteWrite:
  - url: http://vmsingle-vmsingle:8428/api/v1/write

  resources:
    limits:
      cpu: 500m
      memory: 500Mi
