apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: victoria-metrics-agent
spec:
  image:
    repository: victoriametrics/vmagent
    tag: v1.61.1
    pullPolicy: IfNotPresent

  remoteWrite:
    url: http://victoria-metrics-single-server:8428/api/v1/write
