apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics-alert
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://victoriametrics.github.io/helm-charts/
      chart: victoria-metrics-alert
      version: _
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
  values:
    image:
      repository: victoriametrics/_
      tag: _
      pullPolicy: IfNotPresent
