apiVersion: v1
kind: ConfigMap
metadata:
  name: victoria-metrics-datasource
  labels:
    grafana_datasource: "1"
data:
  loki.yaml: |-
    apiVersion: 1
    datasources:
    - name: Victoria
      type: prometheus
      access: proxy
      isDefault: true
      url: http://vmsingle-victoria-metrics-k8s-stack:8429/
