apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics-single
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://victoriametrics.github.io/helm-charts/
      chart: victoria-metrics-single
      version: 0.7.3
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
  values:
    server:
      image:
        repository: victoriametrics/victoria-metrics
        tag: v1.61.1
        pullPolicy: IfNotPresent

      extraArgs:
        maxLabelsPerTimeseries: 50

      persistentVolume:
        enabled: true
        storageClass: rook-ceph-block
        size: 500Gi

      scrape:
        enabled: true
