apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://prometheus-community.github.io/helm-charts
      chart: prometheus
      version: 14.2.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    alertmanager:
      enabled: true
      strategy:
        type: Recreate
      image:
        repository: quay.io/prometheus/alertmanager
        tag: v0.22.2
        pullPolicy: IfNotPresent
      persistentVolume:
        enabled: true
        existingClaim: alertmanager-data

    kubeStateMetrics:
      enabled: false

    nodeExporter:
      enabled: false

    server:
      enabled: true
      strategy:
        type: Recreate
      image:
        repository: quay.io/prometheus/prometheus
        tag: v2.28.0
        pullPolicy: IfNotPresent
      persistentVolume:
        enabled: true
        existingClaim: prometheus-data
      # resources:
      #   requests:
      #     cpu: 100m
      #     memory: 1500Mi
      #   limits:
      #     memory: 2Gi
