apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vernemq
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://vernemq.github.io/docker-vernemq
      chart: vernemq
      version: 1.6.7
      sourceRef:
        kind: HelmRepository
        name: vernemq
        namespace: flux-system
  values:
    image:
      repository: vernemq/vernemq
      tag: 1.11.0-alpine
    replicaCount: 1
    serviceMonitor:
      create: true
    service:
      ws:
        enabled: true
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: https://auth.zro.io/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://auth.zro.io/oauth2/auth
      hosts:
      - vernemq.zro.io
    persistentVolume:
      enabled: true
    additionalEnv:
    - name: DOCKER_VERNEMQ_ACCEPT_EULA
      value: "yes"
    - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
      value: "on"
