apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neolink
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://k8s-at-home.com/charts/
      chart: neolink
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: thirtythreeforty/neolink
      pullPolicy: Always
      tag: latest

    config: |
      bind = "0.0.0.0"

      [[cameras]]
      name = "garage"
      username = "neolink"
      password = "${CAMERA_GARAGE_PASSWORD}"
      address = "${CAMERA_GARAGE_ADDRESS}:9000"
      format = "h264"
