# yamllint disable
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: github-token
    annotations:
        tekton.dev/git-0: https://github.com
stringData:
    username: ENC[AES256_GCM,data:73mm75Bq1OOo,iv:rLnONE/Jaho8N0+8gOEegPo0f+kg0h6Ah1GAMNTZVcU=,tag:pjjY/QKKU5ol9bB7VGdEug==,type:str]
    password: ENC[AES256_GCM,data:cKrpgwqzSLB+FQZ+2KKohvVzA356UQGC+yXR6CxXTFZwAOfV2mxkRw==,iv:JxkMO6TRtE4ma/1Aalcnww58CIn3RyESWkeZxlxBz5Y=,tag:vq1c6cHyCZVyDzD/xsjojw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-07T17:22:09Z"
    mac: ENC[AES256_GCM,data:bhMP779EgE6EIlV/vrHGaxRQL0vbOSea9QGvp25uqd3xtG8MLm8LTDUVR5cACT4Jxui7UAmTwLK/Ao+Ku4uRxWq1uiz6G7Yf/oLelnYyo21busVM36vyC29O3MbsR/nMHaCcgGUVH7rJK10E7Xn2bj+LXRdXTMJocsia24XQzrU=,iv:nIH4dy635LO0QkP17Cns0zyP6IAW7uFeNXPyfUFIvCw=,tag:ln3AMrqMWmV7079cRUqvEw==,type:str]
    pgp:
        - created_at: "2021-06-07T17:22:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DiZ7E0TI8O2gSAQdA/ixUUsZBDhsdLTt7QBFv5H/oO69t76A6bNno2vDlaU4w
            TSN+4bzGJdIYlZLn1ddGujlPdo4vmtFc+wd4g5eZemjJtrntzQ9p7ISPAj0mgQjF
            0l4BzbV39TTvjZLDNZehSdYPKGMggjIe6UZleVNAn0ZV48/sDoYBAr8kk3gDh70l
            PPalaaedQoT6iJE/N33Jauq8OWkm1QYyABcSW7cICZqbZHU/a3LiF7Sq2MSxi0NB
            =NXsk
            -----END PGP MESSAGE-----
          fp: "0x4B9C178B49228EFD"
        - created_at: "2021-06-07T17:22:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3xGBpO+04gOAQ/8DceIHS6Wf6Nq66bRkBj7WqZthPhwhIJz0//V8jsxM9YL
            gebjLzp+dX83l/c+KbLKzGAv8EQWcUV+O2BHMwQXArG/d+1EardAa0Ugm4wJRDwy
            EtXAxpNasm2pzyynRTX+TVCUbAEiVbgf2xXAdraUsyCPmEqIUKHO/eBZMkw3MIVh
            G/GGzjnKhIhcMwmcgoCoUedX6Wv2tc/+coe/zKA5NRk2aLaDV3kuXHGBiFvITaxG
            OFyuE6QqO0j9dpIhBY44h8M6igM0MvaHbfKUZBJapqSDUEGpJEY194GLcM1pLbEh
            Q/7eDDmaB2iRorPOdTABT2C8QBgL+Duy778KoNnyTOwRHihc6kwy7Bt7vUnGsxSS
            pw6mfGmUJonT6ARXAIITMXdKZ6ZeFKO0VIwz85kh4PhL6l5sofx2AFd3JNBTbMPs
            RGeC4mOL80hfeJ5dUunjN3ushB0/ettZZNfwkF81BmkELkl8wtu8IzA4kp0KmhsF
            kE33SD7eQQWyaB3RlC/tcdhMSJyrUcPxkS2SrgJKo6MG9GDv3Ycjs93OkTIASazX
            lEI4L0A+PmGdhckMe8eBSKAGd3iihEW9RgVOrnxv+BYSEd9CoDV7f/aJs0959Yk3
            cYstQXPtAocjrbFQEi+VwfmgdlRuGa57712AidDKdoiAneBvH8X+WpTxQVWHrtLS
            XgFsJrFN2gA1EQW1bMJIPHD+lYB1OWsMdEHfoaQNjz3UXw+O88ZWQRgefp1Hd7nS
            YfQw38lrgH40upDIdisooMmhKt2xCBHk+0E3v3J8U9thS2lywnflykyAqNa9maE=
            =mP0G
            -----END PGP MESSAGE-----
          fp: "0x47262D3D407ED16F"
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
