# yamllint disable
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: harbor-token
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:G9je4fZuT4I0f1WbKgJu/s2pLx/ic6PNZxxuve8f8866ymMi6k0S2UgjFKxTz5lsa+hq9ti0hMaYj8ruVeGoz/+5sS2ug01QL5K8HWZq1mPPE1pZo2RFTUQwHK6RNncgSyWWfH9e+uGn5Ra5NiRLPDvNzOm+RZdk+GMVTe9ml4tKYdxhUyy/SrLob7tPYhjhlXt9o5OGuyXBh7jVJ6IR0oRI8QELCBRDoKW/FWRe5vXD3YZlHnHNw7ezEHjiS8Y7i3UTS5UQDtGdinahVf2CHMEgWif7M+sc5gk=,iv:NjS3IRQpZDU/Mlz72/j1WKUjXVfya5pOoRlY3IRIWJs=,tag:jfJ7RIT/53Sk8truoDPzZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-07T17:22:19Z"
    mac: ENC[AES256_GCM,data:N1iwxu/JXho97u3KWecN5lmLb8K3/28pf57Fr5gwWosJACae/HCQodXa5XbHeM6ZISZvqfKdNUIKdLd61FnQPe41vkR8cAmzlt5Hnrt8FDB8PXppJIfD/AA4Y0aWUA/aNTSDpk/fx65C83dZCOWXrsAYSZYAaNW01sYbl05F+L4=,iv:VyoFqcvKgoWRQqnPFxXTLBIq5Y7gMBay8pqT5xCwrRc=,tag:Pc8J4c7UbBUPezRmkffUmQ==,type:str]
    pgp:
        - created_at: "2021-06-07T17:22:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DiZ7E0TI8O2gSAQdAzcWIEPPKbUQn/K4SijRgkruJkxBLsGSO3W8NX45ATXIw
            Cyg+2jQ3D8rvZ9eEUIsPhNDQ5eWP1rjxHsDk4+9o/YOMuyaCrB1QmtlAu2nSAd1/
            0l4BMz55TWbBX4K/HRq28Ijz72pr0aX5knstJX7yaqw4oyvKQgW8F0HEpyQtZ5ix
            kpHBuMysgAUiP/VS2Y50eVH92tdqYxDNuMhZYYEOiTDhREwSXhiFHwT6aCdeY6Pe
            =6hqC
            -----END PGP MESSAGE-----
          fp: "0x4B9C178B49228EFD"
        - created_at: "2021-06-07T17:22:18Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3xGBpO+04gOARAAit+zgVIJ83Mo4LjOjJ6JvFK4ZAl+PgbUWBWwPNK63I76
            NtFWx/UaPTdvt5s0WpX3SB6FfMrbSpwzdXWed+1WqhtvJx4C3Osg9MDkFc2yhTWM
            wkUI8QzWvEox3ZIZzxZZKzZdXjVZ7mD3S0uNBdwm9lK5i8s6IsTkrazuOjUmNzQ9
            vxT3Aox6BnXGDC/FwedXyTcKg1WFIErZ9NrWtQl7vwwrHEhWEMcGbobvwPgfcR85
            haYPMMmTBRU0A9JNnwpISAatQLmHr7CFHv0oYcSEDYPMBgTh9vbY69inWSI05SWF
            lbbP8FkA2YMbY5vLEkH7L0k5xEIOtRVkjvMW89GbCL5bwm33B2UCYlgncvWeQTdJ
            Oc6y1vpOxEXkh/tNxCrOSE0Oo+1RIqGiNozRU4mokXwcOV8wrfn5IurdrgAUEtQj
            +FiqQiiHabKqBctDyAJ6nNvDVwGxW6H5Qod5nH29ViIUwpK7peQLsQ29LLMq/T9m
            OvhX8lzER5IarhzX0QU479FFHurTB5MGMPgATaHFkbyfv5ZN0ipr/Bs6fkIfcQDA
            BrMP6QpItCxcAZgdybx0FhFHWtjThlsNwHmCyoMfYKjZwCAT7X/fv3F9evtOuDi8
            0XV032K2cc+WlNR4vCBBbQHOd9ar5dewdIk+JZISrcAucT+0Do7TeGTDLOc8FVLS
            XgHHdvNL1Ht7O/8TYPI2l1w7qx0x18VrmE10eeKVZfAUwJunptzCX9BEE385nu6r
            2Mz1Rw2G6mv/HBXKRgrYmHmoHqQEW3nF5bj7CByCjV9ILXwUcGEN/pitycTekgM=
            =mZBa
            -----END PGP MESSAGE-----
          fp: "0x47262D3D407ED16F"
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
