---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nvr-pool
  namespace: media
spec:
  accessModes:
  - ReadWriteMany

  resources:
    requests:
      storage: 2Ti

  storageClassName: rook-ceph-fs
