---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: media
  labels:
    backup.velero.io/schedule: config
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 8Gi

  storageClassName: rook-ceph-block
