---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media
  labels:
    backup.velero.io/schedule: config
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi

  storageClassName: rook-ceph-block
