apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://oteemo.github.io/charts
      chart: sonarqube
      version: 9.6.4
      sourceRef:
        kind: HelmRepository
        name: oteemo
        namespace: flux-system
  values:
    image:
      repository: sonarqube
      tag: 9.0.0-community
    service:
      externalPort: 80
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
      - name: sonarqube.${CLUSTER_DOMAIN}
        path: /
    initContainersSecurityContext:
      privileged: false
    postgresql:
      enabled: false
      postgresqlServer: postgresql
      postgresqlDatabase: postgres
      postgresqlUsername: postgres
      postgresqlPassword: ${SONARQUBE_POSTGRESQL_PASSWORD}
