---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sonarqube-sonarqube
  namespace: sonarqube
spec:
  hosts:
  - sonarqube.${CLUSTER_DOMAIN}
  gateways:
  - system-ingress/gateway
  http:
  - route:
    - destination:
        host: sonarqube-sonarqube.sonarqube.svc.cluster.local
        port:
          number: 80
