apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: registry
resources:
# - harbor.yaml
# - service.yaml
# - ../../../../shared/postgres
# - ../../../../shared/redis

generatorOptions:
  disableNameSuffixHash: true

# configMapGenerator:
# - name: postgres-init
#   files:
#   - create-databases.sql

# patchesStrategicMerge:
# - postgres.yaml
