---
apiVersion: v1
kind: Namespace
metadata:
  name: system-knative
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: knative-test
  labels:
    eventing.knative.dev/injection: enabled
    istio-injection: enabled
