apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 3.30.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    controller:
      replicaCount: 2
      extraArgs:
        default-ssl-certificate: "system-ingress/zro-wildcard-certificate"
      service:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "${LB_INGRESS}"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
