apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 5.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.24.0.4930-ab6e1a058
    env:
      TZ: "America/Chicago"

    persistence:
      config:
        enabled: true
        existingClaim: plex-config
      data:
        enabled: true
        type: pvc
        existingClaim: media-pool
        mountPath: /data
        readOnly: true

    service:
      main:
        enabled: true
        type: LoadBalancer
        annotations:
          metallb.universe.tf/allow-shared-ip: plex-svc
        loadBalancerIP: "${LB_PLEX}"
        externalTrafficPolicy: Local
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        gpu.intel.com/i915: 1
        memory: 8Gi
