---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: plex
  namespace: media
spec:
  hosts:
  - plex.${CLUSTER_DOMAIN}
  gateways:
  - system-ingress/gateway
  http:
  - route:
    - destination:
        host: plex.media.svc.cluster.local
        port:
          number: 32400
