---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: radarr
  namespace: media
spec:
  hosts:
  - radarr.${CLUSTER_DOMAIN}
  gateways:
  - system-ingress/gateway
  http:
  - route:
    - destination:
        host: radarr.media.svc.cluster.local
        port:
          number: 7878
