apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwavejs2mqtt
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://k8s-at-home.com/charts/
      chart: zwavejs2mqtt
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: zwavejs/zwavejs2mqtt
      tag: 5.0.4
    env:
      TZ: "America/Chicago"
      NETWORK_KEY: ${ZWAVE_NETWORK_KEY}
    securityContext:
      privileged: true
    persistence:
      config:
        enabled: true
        existingClaim: zwavejs2mqtt-config
      zwave:
        enabled: true
        type: hostPath
        hostPath: /dev/ttyACM0

    service:
      additionalPorts:
      - name: websocket
        port: 3000
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/auth-signin: https://auth.${CLUSTER_DOMAIN}/oauth2/start
        nginx.ingress.kubernetes.io/auth-url: https://auth.${CLUSTER_DOMAIN}/oauth2/auth
      hosts:
      - host: zwave2mqtt.${CLUSTER_DOMAIN}
        paths:
        - path: /
          pathType: Prefix
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: "feature.node.kubernetes.io/custom-zwave"
              operator: In
              values: [ "true" ]
