# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    namespace: flux-system
    name: cluster-secrets
stringData:
    #ENC[AES256_GCM,data:L2aKA7RFR9KJQQxnjBNR3pwXXwKSzGCqLKO0aqHd2rS65GUW/j00NFajGM8jCnmsmcFL6KTdskM=,iv:DD4DI0zP3zcLyZ3y+265QlkEYIIewhrCHqUjZ8lVXzE=,tag:ih/6WOY3CAZSpS8pcBtMiw==,type:comment]
    USER_NAME: ENC[AES256_GCM,data:DyCgcALkHA==,iv:CUsUGwhTJyOdExmSQtovNvtXmZoF98Eocgt34VFvuwE=,tag:uiLYeY8MnfHz3sF2Cs1vjg==,type:str]
    USER_FULL_NAME: ENC[AES256_GCM,data:hRhaZZ1Q5nVrnxAQ+bkx,iv:EoAQBeA9m0wbnjFTe/oTTUgpUtLfbiFFlThBX5TOzkk=,tag:6N/DX1INaqBCfB04Slv9sg==,type:str]
    USER_EMAIL: ENC[AES256_GCM,data:+YROXj2YlPR9UXru78iC7b2PsA==,iv:IYh3gpIyE1ILwzgA35zg/dEwHO4Ahhch9umAns00/cc=,tag:tCsmb+bnYUyziNfkX5aqKQ==,type:str]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:oGqW3hpL,iv:4hw+pLSfYjjjKiBXH7qKjK75bWVvswgxe+ChJ0bAAp4=,tag:ax54DXQHezopPDuKQACkKA==,type:str]
    KNATIVE_DOMAIN: ENC[AES256_GCM,data:hiRpXUL3nA==,iv:ksKBhwhIuZ5PLol5WotxkC9yyLr5s0bGKxVvFZD3TDw=,tag:qP1dDXTPySrUM65s45/pRQ==,type:str]
    #ENC[AES256_GCM,data:IAKDHRSwEHrbXf2STtEEG3ApFxzF8KUWtm+J0w==,iv:16Ups5iGt0OklPn0WYCdxc/a5hdCgnfYVVEpISRyo38=,tag:TMlHUJAw9L8WIoNcI4VxIA==,type:comment]
    KASTEN_K10_DR_CLUSTER_ID: ENC[AES256_GCM,data:AjUOe28vXfk/QarCDO/TUPwkZnhCthSc6HCwhJ0y2d2utWdh,iv:hICJ04cKp2eolDyaU6tzXdkROs4wMRY5RBItR9asC+U=,tag:9GcRXxX44GHwQe3lNRHTlA==,type:str]
    OFFSITE_BACKUP_ENDPOINT: ENC[AES256_GCM,data:faPnl9fsIyV34AZex8ZtPNZ0aZIKQb0sAq2ofRzeiUcXrTCKsOg=,iv:Ps9IF2NwKyycDIbXAJvptNziJebJKYv44QdxXdKSaSM=,tag:mhbfjc820BxdUnWDBG6KoQ==,type:str]
    OFFSITE_BACKUP_REGION: ENC[AES256_GCM,data:Vc82MTM7ozeLz1A=,iv:RisgviS+8cRutOhkMK6pO5nrwqLV775qRxgpDh0++3M=,tag:hn8Nga1gP30K5Aze9+Fe5Q==,type:str]
    OFFSITE_BACKUP_BUCKET: ENC[AES256_GCM,data:XvweboTY2HfLJcmJRePLGQ==,iv:PNE1dLF6vWdsCOKOoWGo+95d6Inemon3uB5DzqYz4SE=,tag:MiZDah+s5U/9s+7UomCZLQ==,type:str]
    #ENC[AES256_GCM,data:ny/2KVkD3fRMygbn99MKeGNB1ALCZ7d3KwLBVxTr28JfjxYWPV1K6WfgDruQ,iv:HocFdc0Vppj5nL3YTsbnkXJGotZj8Vp0p3UMgw2w+cI=,tag:Mt4xCVYn/dePicETy2OZ1Q==,type:comment]
    MAIL_SMTP_HOST: ENC[AES256_GCM,data:+kCpUMX57U8n/dEQ1dh5rg==,iv:EQzsvdiUR3DVJxLKjSDUATqtJB4he1U8lX5jgRhM5bE=,tag:M8UTiUyK35VkFkcWlJ5vFw==,type:str]
    MAIL_SMTP_PORT: ENC[AES256_GCM,data:5inM,iv:ap6feRfbhNv+5mwwylmqOERj/yBL56dca6InTzxbGJI=,tag:wrqMenxWBfLbWI0XxCyQJw==,type:str]
    MAIL_SMTP_USER: ENC[AES256_GCM,data:YZSGRKAtrTk+HVEV/3/DcLw=,iv:sQb4BRRA6NqUr0bv/JTe17rCPb2lAkK84I+MjM/+EeM=,tag:QepsapdI0w+iNFSppoeYHA==,type:str]
    MAIL_SMTP_PASSWORD: ENC[AES256_GCM,data:ss/vl54wiAoxfFF4M/Zy/On93Z518yINTCny5uE15zE4dsOXLHbSvDgHT/hcZ5zQdr4=,iv:2LCRTfAGwjLIUz0nf6gRXpGpu91+GMxlhUCWXl9S+YM=,tag:iSXwNmb8s5FY5kowGwJwtQ==,type:str]
    MAIL_SMTP_FROM_DOMAIN: ENC[AES256_GCM,data:+96MO7VP,iv:Kki9MtYwxezSELAmC8s6KxaLR5BG4/h35mLlNAAHnMY=,tag:PdUOAPXYvnMigxDftgSH6w==,type:str]
    MAIL_SMTP_FROM_ADDRESS: ENC[AES256_GCM,data:TdIoHi9hLLob9rcBPOs=,iv:IjotW/mc6wsVk9+U2SJbwlnJjg1z4oCqATlxhSX6ro0=,tag:27tjQ04cUAWPQhRx9JRLuQ==,type:str]
    #ENC[AES256_GCM,data:WxdYorCui62tIo/eo8/hHlMT,iv:zFnjz0yMlQeGiM26UWlM+CHTwju8lx1pPLcdl2KbM8M=,tag:PsigeCAszw0XYGUdAxy8yw==,type:comment]
    PROMETHEUS_ADMIN_PASSWORD: ENC[AES256_GCM,data:ZkcdQJTxNGXeZQQws3sHeb5gqMvroL1g,iv:am2WrSVlk4g5xBVAqu+CMbbIVEbbAxj2YsT1fPTNWdw=,tag:o3eDglvA3nBlKU5RAnQ6Gg==,type:str]
    #ENC[AES256_GCM,data:rAl6Dg21w4iwNLw93bd6ZpVDSCZG,iv:T4A36FriQvS2g3PpDbbAU0+rFxxmtX7aBPNg88g2j9c=,tag:+AGTvZ6hoFbbY7G1tgCXhg==,type:comment]
    OAUTH_COOKIE_SECRET: ENC[AES256_GCM,data:T7TAOAp1bfd9lUv5RXHZlaY63ifCor83cwXkFiKxd8ow2Et/0ov89kh4JIo=,iv:yyMGN4QrZcXS9gp3+hKqJxBTMgo55f3sSzmx4Jsm4AI=,tag:IAzKYg6qQXvT03TVs5WjrQ==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:Q3SZYPTfXBeByAmSDHe5bX75eNQZFqXmO85kwI6l8uE7DQjX,iv:yF76m9AOZXWudB09L9h/2k4BkkcQDio11J1oGrSVDhY=,tag:eks7RgJcZ83mG1hpuXXLOg==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:/lPNkWZWmpo0f7nnD9XM8vz6bitq8o9zmQd52+fUjvTJ/pbeok3MDIMsJ7U=,iv:Ce2FB+nyvoZSMM5vGNdBGHVvdFAuv6L48ljO9xuFyN8=,tag:2wq3qVF8qpZNtwxxriic0w==,type:str]
    #ENC[AES256_GCM,data:DZ2xMi3Zlxh/f3fuPZAdIM7rOIQHCnl0,iv:FiLP92vtQMKy2ycIfWY4l1yPZs1TjDYIGzRMOvS1i1k=,tag:60d713vt5PvdAzcsLFMjaw==,type:comment]
    HASS_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:r9ahzunCRl1aUr/QCHVZqKnIVmGLhAaX5Fx4Kw==,iv:X2Ccl535bXdDcqUXCH6ZQ9YGj5I1asd3NB1BySm5PKg=,tag:fVDasb0UOVsFbjHQQ1bHEA==,type:str]
    ZWAVE_NETWORK_KEY: ENC[AES256_GCM,data:GqxXH9LLZS0C3YDqew7ZkTamlsNRQOOW17opRfokbCI=,iv:QcqC0ZqoCULJHIOVqFUPTUKPksTfWA4lwXp2cEq82XE=,tag:C0JjFDo1T0xnefEcmji1WQ==,type:str]
    #ENC[AES256_GCM,data:hsk4EvvAxwGAdf13BK+CvFCQ,iv:UEKDK2mlaVK/y9qGIgt850Q7I9PzGTFqku76FH+whzk=,tag:85KaNZcLW1VoWfrb+jqtsw==,type:comment]
    FRIGATE_MQTT_USERNAME: ENC[AES256_GCM,data:TcfnFz+gbA==,iv:h+WNyN09EsATiopyj0NvZw3NlgI6Z8KmP0r/mLk1MVA=,tag:cLhXBRy62BjnhsqtL9d/cw==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:fkmEWCuR3BxElXCQzSKaZ3s=,iv:tlP749VIJLxSJi/t49YL3zsB4xYjlnxAfDqtB12a98c=,tag:yll9moUp2wVRcaaoUhl1Cg==,type:str]
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:qyy1cAKTdG1DM72/ZRsM5wCb/Ofg3GGYdZbTLR/baw==,iv:ogrFym4pW6CcjjBiPGS43n75Mdn/mTAP8RNnbnJB6f4=,tag:JK4WW1ffz79dDbIDw9ucMg==,type:str]
    #ENC[AES256_GCM,data:Tov+aPSoBNXTUGhssWUPZ1HdJtO7nCbDXg==,iv:fu/qTk4AWaPcXeZpECR4ADcfbwmQCXR9fJvEcglEULY=,tag:VckiU1V+TjMFfpskyO67kA==,type:comment]
    CAMERA_GARAGE_ADDRESS: ENC[AES256_GCM,data:lqAIydVP9gfRFEBb/A==,iv:XWQpEpYAkK8t6wWDkubXiQ1zqn9JP4W9XavpYQQzGoI=,tag:Zd8r6DoI4E/yxq2oTmfFWQ==,type:str]
    CAMERA_GARAGE_USERNAME: ENC[AES256_GCM,data:4muZwL2bQQ==,iv:GHUajNpJ0b/vArkgRW80M/dqPltobses2ABqAyck3dI=,tag:OYCr3/xUrWk9hFwkMzgy2Q==,type:str]
    CAMERA_GARAGE_PASSWORD: ENC[AES256_GCM,data:peoEUKt+59ICBUT4,iv:jxMXiElwF+0uAEIkhU+9YsqHQ8fCKhyUx1/B9fPZY3E=,tag:e57YZGTiMnrbMN3crDAHAQ==,type:str]
    CAMERA_410_1_ADDRESS: ENC[AES256_GCM,data:v1SIK6FToSw9NwuI,iv:TY8ViWkUXRmZWpTJexyVoI6ip2SAASQc6L2YMb/0WFo=,tag:0he4kZHUOptboZf/whnA9Q==,type:str]
    CAMERA_410_1_PASSWORD: ENC[AES256_GCM,data:2crWo7TyvCRBiBb7rmpnIA==,iv:oNFgYL3FtXVmNh2po7NMYWG9ArEvAuKjU22ZVe1PoZg=,tag:eCJhE9jv19i2KBWXVcG7+Q==,type:str]
    #ENC[AES256_GCM,data:VzzXzjBAosfBw7cGqpPHzSR7iH7iEHIKpxo=,iv:pfaZC976xK6L/cG5V6/8WYDvhCb1QKvYIRbZD1OG9AE=,tag:F7XHnPfzMcmeHx4kOe+4Lg==,type:comment]
    CAMERA_410_2_PASSWORD: ENC[AES256_GCM,data:UyYpSlXQviuq6dGt+QYkGQ==,iv:llMeNIdVOjYkA2X1J+/HkKUXpOS9o+H8ipcQs+Ic48k=,tag:xVw4RoGpbl0mLL7ff8+uWQ==,type:str]
    #ENC[AES256_GCM,data:kY/DwHwjqxPJMFhacCVJ4uV0,iv:aM3hYql9XPaF5eHicqmzeLcbr6HSgegClZrHQo7Es6A=,tag:NpYQr6C9zYE31fC0UBxEhQ==,type:comment]
    WALLABAG_POSTGRESQL_USERNAME: ENC[AES256_GCM,data:CzGSkE076fI=,iv:cfO6RrN3iGUzf9FNlL4Ep+nn7iqFvmYUq1jzsiR8BTQ=,tag:07OtJcCbBhXOugXNIMMbEQ==,type:str]
    WALLABAG_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:sUgVCP6mav7123mKzpmndVLtSCW9AxiXIhyXKoGt,iv:dwevLVpJtY/v9Twe+25erU5SFRLikq9gd+UCfkZJMRM=,tag:F5+TAPt0o9fnBrQuP5MQhA==,type:str]
    WALLABAG_SECRET: ENC[AES256_GCM,data:LctI7SUrp4JxtAvs6S2zZ1oAmlyoFhr8DvmtLoZporp5+XYh5oB2VfoNpsmaEcyg6J4=,iv:MBE4LmM+KY9kNHZ0t/dvk4JbueMUbK9csqwQfQDa2kA=,tag:DB1/Eia1B/n5gw4tI/ekmA==,type:str]
    #ENC[AES256_GCM,data:9qRctXNy7aRBYw==,iv:QLIgNwiafLoS/A4yrffV6t7iRRGjIuNTs/zpLhHiaGQ=,tag:LggzF75UDt8gxdQy3Itw5w==,type:comment]
    DRONE_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:/UenySvRZegjzVALJcQy/z01hBYHWNNVoW/OKdQhG7dG0Fts/GollrsuPjyTAcU=,iv:EMDtKQbulNwotZTsShz4QEgaQ2QFEb1CTumONrSLiqk=,tag:PtLK2fNU7V4DM/r0WOeA/A==,type:str]
    DRONE_GITEA_CLIENT_ID: ENC[AES256_GCM,data:EJnLG2YO9U/jR0TryE9qB5LoSbNAUW5q4a1pJck6dXm7Pfrd,iv:auGN90pQCufNRl47Xs2L82+SEXSLnI/ivhM15Bw0pPY=,tag:DAcvyrT5wRbSlpP2GUdTuQ==,type:str]
    DRONE_GITEA_CLIENT_SECRET: ENC[AES256_GCM,data:ed1DZ4s0/mO7n+/bXsOioyPxlxz3E8XvGuDwaHDbOuXeLYaqMdNHgJIp/Ro=,iv:7v0UZ89b+JcasQOI0631IfVQrum2sGpWSy7ge0wpk6U=,tag:VFdfXtAB9fdACJflSjfmHA==,type:str]
    DRONE_PLUGIN_SECRET: ENC[AES256_GCM,data:Gd3IHDK5GuC8Yi4WVn07gWXgQ/dVU99jPuYVRCRui59A8/j9fMOdJXwjnSY=,iv:vIVaehiU0+dXIjlpjMBiv9wgeksc8aSFaCh50EbfI7s=,tag:8tkmgrwouihdS69k18jkkA==,type:str]
    DRONE_RPC_SECRET: ENC[AES256_GCM,data:yoJBUzP8Pd6lir6nlBnfqR+G2NU6Vqk6/khKId1VWxVLMxv/x+cjxhA+PUw=,iv:Z7zKkzGcU+9QbS5tc0ibYAo6a96B0g2mDhgNkGbKsso=,tag:CZHhZUFS+yNxtNADnnCOxQ==,type:str]
    #ENC[AES256_GCM,data:TQwtYeBp8z5Zntg=,iv:3HN9r4i09D3luq2vDTCjGdZwEw7b+2TQq6aE0b8GeI4=,tag:3vnvcL8nVbGg1Zk+Jq2YjQ==,type:comment]
    HARBOR_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:Zalb+LxN1g8/D9g1n9mKMS2QUmXfZ0Ydw/gWNOKJfvkDGa0MnAk=,iv:bkEJCDtzeOX1rgpirhhgUYRu1qXW8wsz8y6jRNIqoQU=,tag:LVzcXiTE3oUxZD1cf06H0w==,type:str]
    #ENC[AES256_GCM,data:2DFlo4Ma7GSqJg==,iv:N5Dopr5mMT2VZGW7aS3fjTYIrHnotmsD57V1JJXKbAg=,tag:4kzC2RR5uGiKdto1W8szgQ==,type:comment]
    GITEA_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:o5F194hql309EaOrdv5lrdlGjkydQG1dmSQJqdsd8q4JFeL7csM=,iv:0I15c9S/iwZxRLv486jUlx/ilm3s/34FIgJuKoAeddE=,tag:DYHvCa8XuL7187WRUX/qwg==,type:str]
    #ENC[AES256_GCM,data:Ecpf5m6SLDRUzHcrZOw=,iv:T6+nwVdfIagZQElb3UbJR/3bUGMj1mgiKDy31PFhw2g=,tag:OE38WxN0lQ/OLNWVrrXnmA==,type:comment]
    SONARQUBE_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:45LhEFc6tOcr3AAQ2tV4X7VrZ8AW8MIZuKfHTczFrH6wn20NUX5H8Q==,iv:tV2HFvkDKlcsaCfZJMkyMPyEMYhoRTf3nHU0Euy5TOU=,tag:XUNGtLNIfQmB82eUbKMWiQ==,type:str]
    #ENC[AES256_GCM,data:SaZBfu8eLUbixMQ=,iv:c31dzrNmNFY7GkP9urroQJwSuqtpBlYpajEZMmiT2z0=,tag:44MauoR+Y2tU7UGQkbLyKA==,type:comment]
    PLEX_CLAIM_TOKEN: ENC[AES256_GCM,data:FhBI7B1t8oq35KXQQD2qxwh9YQ0Q+vrwH9o=,iv:ucvxoGxLL/c5ylLE5AiJmwsVYmhM6pXn1Pjda7MLXG8=,tag:PieAggX10BC3Y5eKWYju6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-11T19:59:05Z"
    mac: ENC[AES256_GCM,data:BPpSrNtFV0IFL2AHogG4WY4AJ1j19QSXpNZPkmik180M6Oqmv46DZSBZKTD8/FB4o9XL9SeEG/9aETv0uP4C2JMserJy2xu8Bcb7LE51CwmRIY+879vQGXNHRLyH7WUtCkzK6wzCVm+hQmzwIBks7GIETvzg2NRmK+6NHiabMys=,iv:lj/d01fIFM7eoikWhmPEOMRpybDcr3Zv3SJ7TX/yR0Q=,tag:VyTdfGuuItMD3NvMMkT4Dg==,type:str]
    pgp:
        - created_at: "2021-05-27T15:49:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DiZ7E0TI8O2gSAQdApM8a5clsm1hFtVJUOoMQuZFogDugZwrF23aw5poJ/Bww
            hzKFHMn9CjC5QcIl7W2vuzdi+CZbS9eyweMlgr8kQY/jgtxS8a80jds9ERgJ4Jlm
            0lwByPbpwrh3BLckzKUIHA9KEbcF2ltL93sSfoYB2N/iPo2HezvZ/mMKA8I+Sp0s
            hZeanNIQER+t3rdy1LXIzcuA9t0fgMqs2HyBXgWSDTA8vuIv6zF0qizs5kVcJA==
            =ixKu
            -----END PGP MESSAGE-----
          fp: "0x4B9C178B49228EFD"
        - created_at: "2021-05-27T15:49:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3xGBpO+04gOAQ//SoqzRlO3LCZ+hlm9xINuvygC1NB+6UpauGWJh32h39L5
            LCwdbSjhsjUIUtskjZv/FBRFEFFl1jB1mVM6HAGCBpTLMov82o9g/Kfx36qxtDDw
            34L2rJdKdZQme0zcB0WOOnvdzsWAhoHrcEoDtSIjvTIyYToyUQMy2sJMWbXC/z8h
            kCNS525U/x17OJp0BcciBlFh9/XzmBq5PB6Pv/GDwa+Eo0BjRgZkCGgSWEzOj5gj
            xsevkyC3ZKG9eS/pAM3V7Op2vJC+VnckFk0MdpNeFSC012Hm/H2xBYQEojzE2w3Q
            MID1PcD5XiVv1dwudAoPRYVyILwQMLOvEdKYcSaEeQK0a2p0DrWWLPjFUc8vOvQG
            YPvrh6KUsMV7W4uMvZkn08mptfyfqQ4a348qO+KrEDHokNdtAZB6sfy/8NyLj+yy
            1O72yJQ6BfeDEilwV+milbCDQY0thzHSR9ZAmsIblasRVwpbjm7TVDO/iCWx/vxJ
            Qmm33XZEa6oUGmJKpp7k8k3B71It1bR0aXkbL70WUOuFH6/e3AvXSLWhBiMN4X37
            CMq7oqjSAEOmQaVJgb2Pj2A17nRyzuRD4q3Lpma3qyQwD9mHeQZzUhj6AD3K6TjP
            2jEHXRe32KnYh8L8n2q+pgFXtMnBH+NeZul7766K/xiKJrxi/x+8wMkr3DTGW7HS
            XAGTGIea/D06EjMSJlg9cgbJ9jE10V7ViAsexzGC6tSh00qE+joa+gDruySYtxea
            hpCNrGeVDN3b5BIA77yirBjH58pLI9b3tgjQyggcm9mZXEi7js55ZVSvb/n9
            =2Tyq
            -----END PGP MESSAGE-----
          fp: "0x47262D3D407ED16F"
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
