# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    namespace: flux-system
    name: cluster-secrets
stringData:
    #ENC[AES256_GCM,data:lUz593kVb8SAorTHkdbbo0EXU8j3DxvxLiza9OSkzIDcumwUAwFXdcg8LfwGOvt9ki9HvtyXEg4=,iv:L1BWxUODapsyTamb4IDJF3OXOXRkVLRD1Z425zRZnO0=,tag:Y0LYaE7C8dJx5vhfxUGyIA==,type:comment]
    ORGANIZATION_NAME: ENC[AES256_GCM,data:lE5Mwf+BI/SHP5U=,iv:DKLvTIbdZcfQ2lFOEjYiwG0qoGvucJfi1+SEJuUc+vE=,tag:CzIczFC/RPxsKaZ97ejhpw==,type:str]
    USER_NAME: ENC[AES256_GCM,data:2Ccc05+sFg==,iv:5wkfo081/eY9gAdRoDUMxOfy+w5Fhc7zctMDakfizJQ=,tag:AtCh6ulUZnOC10wTeuCleg==,type:str]
    USER_FULL_NAME: ENC[AES256_GCM,data:P4tSdEFI3IIABuPaGiaX,iv:udzPqvS7W5veTbz9pTvruCq9dOmgGI+ZqJOq2spVXBw=,tag:BaD1W9kxA8Aox1JoS3VIgQ==,type:str]
    USER_EMAIL: ENC[AES256_GCM,data:062PCJ31szxWp2J5LncGIBH2qg==,iv:wUggj9HdZXgjT1QhJRnIVfCUIlfnNPSJCW4Do5mj224=,tag:Z7e9LUVIeMPPrizaPFJpdw==,type:str]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:C1/pa4lp,iv:ZYT49TA1qJR//bKHky7UsVnCkDu1V8c8p6LEeZ7yU8c=,tag:TnJd8OKmUvbHg/FjW0Q7+A==,type:str]
    KNATIVE_DOMAIN: ENC[AES256_GCM,data:b7GY/qXotw==,iv:FkUwyIDlLskq+kRPF9a28GdWIFkb5XqLS32y/cKEkuc=,tag:zmvplmojyx5Y34f8oGZOwA==,type:str]
    #ENC[AES256_GCM,data:S5nsOHoH60oaBplaWtwHSsJvXDxZmmXZBU3QkzyXcAbG3Cxk,iv:7iFluUWYsNXTmwYlY5mEQxmu7X8sL24fiXs3oxx1Hd0=,tag:hTEPuuDfvCZYqiJTkzNIKw==,type:comment]
    VELERO_BACKUP_URL: ENC[AES256_GCM,data:jIi5vMLm1+pCUX6eGy7Ku5Ai9uOiF7e/cgnE15dk1Wg4hfDvLpU=,iv:vxakXQwcszpAf2g/5ttOHz40gsTwjJUSva2CVsg+BDI=,tag:H7UytRL6ljnhdVDj8/Nq6Q==,type:str]
    VELERO_BACKUP_BUCKET: ENC[AES256_GCM,data:aRkG9W6CWN26pU64SEv9YQ==,iv:4EMo9FUaNvdf+l0sCbFT1OwF/HEDf/0bBwpju2Mt91o=,tag:0h6zVIh54BKrcxLK0GE72Q==,type:str]
    VELERO_BACKUP_REGION: ENC[AES256_GCM,data:Nw2I8wDClnw0VZE=,iv:LA6RldZBCiKaSmnt4vF+IncogjOBY0d8Zgunxq4Bq8M=,tag:DQLTFFlnPnzLluEmnIHXQw==,type:str]
    VELERO_BACKUP_ACCESS_KEY: ENC[AES256_GCM,data:1ErH/omsVvzng9NIbEV18fnJ89JmtFDnUQ==,iv:aWSiCeqA3TZLEHeHSoey8vAkWjB7vTlyEEXUrcro3Wk=,tag:mcIhDQuNtyv1yrho3K1RQA==,type:str]
    VELERO_BACKUP_SECRET_KEY: ENC[AES256_GCM,data:XaLsUtrcg3ANB0NbgsCfC7V8/rAjVGqbZFiVrkezSA==,iv:mKz4IhxPpZ9yoD7VcVpsFAIeLslUpfi/YxvjiczSoXg=,tag:Kn/S/o75Ee8YSz9DJEK32g==,type:str]
    #ENC[AES256_GCM,data:u24RzXrPeePUTALy548HaQwFSK2GCAUIDdDSDFMgQlhxMm+npekEzegrJPYo,iv:ePa0bzgPSpCs9ZUBxKpTJCi5eyhuBPQCtbH+rFnL/4A=,tag:G0zFYjBG9wi4H/S66p7S8w==,type:comment]
    MAIL_SMTP_HOST: ENC[AES256_GCM,data:4LPV+lfsafeWPSeSv0PZpQ==,iv:udf0y21pCVWSz4dWFWQ/U8Iy/JGZaQXFj61/d1CPmL8=,tag:U582HNeq1qR6P2yUWyLm0w==,type:str]
    MAIL_SMTP_PORT: ENC[AES256_GCM,data:dUBI,iv:Oz+JdCUZEqhvpNCxwCz+mJhlN+6SjqIaiDdrgQ4T2Dw=,tag:vvoXqUoeXIcJ427tOdmQtw==,type:str]
    MAIL_SMTP_USER: ENC[AES256_GCM,data:ZGxIUfE31WrDG4W1vVPoqmo=,iv:iPEqoEHdWIHbCDqIDboeNKY2NXGNHr2365QC+AsHnW4=,tag:tmhUr+gHoGPK1ifkD/lnTw==,type:str]
    MAIL_SMTP_PASSWORD: ENC[AES256_GCM,data:XNt5nIPDL0y8ho1edI6PwW8Xmor3Pvq4illp4NnFM/1HgKbiJPSArHVZKicZX4CyKxU=,iv:UHtf/LNlp0T+ia4TT8HVa+XRQtaTUTsob+3D76LpnTA=,tag:jJARTaeMWTBFVJCsTqFQyA==,type:str]
    MAIL_SMTP_FROM_DOMAIN: ENC[AES256_GCM,data:KP1P6pbD,iv:tbmjQ+JdejYLJtudYEJ9qW0VwjnnGVGP76EMyMfzS2I=,tag:Fc8QpC/i3r1xXwSEBSqYgQ==,type:str]
    MAIL_SMTP_FROM_ADDRESS: ENC[AES256_GCM,data:cKEscmnLU+HyBeJKDqsE,iv:EVCd/RuhPF3RIN1qk3GykYpTcIEmDr7quZNDXIfkIKk=,tag:iV/HfHIJbx1s/UurVkTP4Q==,type:str]
    #ENC[AES256_GCM,data:kioBxbmEhP2SEZNfnu2S4MA=,iv:exy/qDZnh02L8bhYAMeY8mTCtYSf/seC1Dtb04rvCrI=,tag:TBK4ixUw5IAnImeKYQ9Tbw==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:6Jz5HEsXwAbi2gUmPHuqI0bS5qpvud0Vw+jTidPuEbN7aFsSj1nLR3tbJN9IaXlz6g0=,iv:Cn6kYmKRYfoUgB56TG7DfjoDPyljCZAklnh/IhWbRHs=,tag:iDVJ/W2CT1HzqNN0kxkCfA==,type:str]
    AUTHENTIK_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:jwE1QzltcNpZtM5HpbitMh4f5jFQ7dVchMp5nLuJ5aqHKbefNoTxTIPtoSfnhoGdDCFd,iv:x/rRdAa77duVwEFOF2zbGyOeUZbEq4LqRO7P88FNkU8=,tag:HJUbdm9B4egK4gR0R+2jOQ==,type:str]
    #ENC[AES256_GCM,data:g75d4BBoL7KeD9WsdASMiYrJ,iv:BFgRDJnrjgXU9Yn8mCMDxzAREm43pzfkBqoocRVUYoQ=,tag:TQ0iq0L+gPbv4gVp42ouVQ==,type:comment]
    PROMETHEUS_ADMIN_PASSWORD: ENC[AES256_GCM,data:9bUO+q9TwNS/ZcT50EylR1dzpl/P+OA5,iv:3maRCkubUL20swDdcl/mmKiar6QZIhDTA9NrSofxTuE=,tag:2eADMFgcD32GIJkp1NsGtw==,type:str]
    #ENC[AES256_GCM,data:d0Zl+zzT9wPZQij2rQv++cEwKzz3,iv:SB0J+jDW7qK2HxXGQjbIs/pLE/DEpKp+5ybg6vpzhmA=,tag:El+IYh0LnfVKhlok0nbDNg==,type:comment]
    OAUTH_COOKIE_SECRET: ENC[AES256_GCM,data:FJrY67HrhMDJuKnLydk1iKZx8Pz14G1/r1GetcPvXvlexVAk7gKNHGTkmF4=,iv:NBeTLcfw3k71gacaiKRv73Wk73hsdNgWiHxNguW8wvk=,tag:UZz+B4jbm299foRRRiByVw==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:fMagld2/vWPA84KJ7Mw/3MVkufHRLq4Yf3DlGP6kL0+bf7Jj,iv:A7sWlSZjNT7rOZa7G07uyHAGwSi0KUDxmtrIWQuUn/8=,tag:TCyzuU5rfVL4q8dx+/tm7w==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:n9gXtrEm0VQ83oQOB/WZqiIDNH16poNhUjPX9m5JwTKFS9x5ODyoW57n8XA=,iv:YfZsvZ3DQyDDB3XwvsxnJRn7/iti2x+Pz2RJN0BNrn8=,tag:zVG5nBl66on4GjxVxmOU5Q==,type:str]
    #ENC[AES256_GCM,data:Jz9XiWaB+wxKvn8Tg9JP5QrpIeNmygoY,iv:X0aiNjLrHzIzxA/xAgMAAvmBh4U2CAto3MeUDcdQzMs=,tag:vH3d4BcVG7PqU46JppG42g==,type:comment]
    HASS_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:IIS+52o9sBjXDgnsYm/fyHpJeFhHZbUJMUZbRA==,iv:ASenNsEhQEQ+01MFf1VBjwF/BBby47/OsAn7EfgEyas=,tag:XmeQRUShHHDR0KBMOtfJpw==,type:str]
    ZWAVE_NETWORK_KEY: ENC[AES256_GCM,data:m4ZQgrVBhbRExQ7oimfJywc5c4iBeyovVQv+LokOLus=,iv:mNJ5LOGYCu49LK/yPs58Sl6TcLKZlcMf3Cv95PnNieY=,tag:E8B+3cj+hVfE4HXCA7FN5A==,type:str]
    #ENC[AES256_GCM,data:hvg+5zOYKZzh3puQwN6vi4x5,iv:lXeey+t5PDB+nFXD5jBIioaiHEptV84uqpgmaq7bcGc=,tag:1f4rJUC2oQpXElfzaI1rGg==,type:comment]
    FRIGATE_MQTT_USERNAME: ENC[AES256_GCM,data:Y4ecmuGOqw==,iv:L8CTfhG5t8Nb0mrVWgXz+g97FvZ64Sk2AYP1fa/rhpI=,tag:75P0uskZ9Hev7Ru4QuCWbw==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:ZQ7cIui6wuWj7nrsuv0y8ds=,iv:6wKqMfDJfUbHl+N8feor/SREOuWN++cVHcIivb/9/Ws=,tag:1VjLpdFpRYidSQL0Tgfxug==,type:str]
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:3iIV4PKSKlzQlwbhr5L9Ku1/FH7jD2Kr1JsRdaQr/g==,iv:snbTAK3vm+K7A/dcyi+58iaULC7FOmeFm1nPLzkAkrI=,tag:kaU3x0YpAtRlQD6zcFEGMQ==,type:str]
    #ENC[AES256_GCM,data:NyhdKf5wTxmwZRTlRcMflMG7aeybatEeKw==,iv:5jfJof/ycZsoWY+RUS3shTFWL0DMdHhda7xe14khXZ4=,tag:Rq0BVLunOpbBZw43+9oN4g==,type:comment]
    CAMERA_GARAGE_ADDRESS: ENC[AES256_GCM,data:wUxQCOA1Eot8Zyd4VQ==,iv:yI6YFBmF2vLycS6u03eUGA5zsmHuWRUfIeOy1ZbLnO0=,tag:FOdw1gU3oy4bir8CYrizbw==,type:str]
    CAMERA_GARAGE_USERNAME: ENC[AES256_GCM,data:F9b02mVYhg==,iv:8sqaqFO/H2hp4TUmcdiRQK32jyDMd/ZqZYbfCWOLWAk=,tag:nK5ajQRfJmXfVcyNnCQ+aA==,type:str]
    CAMERA_GARAGE_PASSWORD: ENC[AES256_GCM,data:4/qD85j8C7zryvv5,iv:a1kQFZ7itx5Ztya3hbaBiOU+Chj4bhCB7qkulv4GzyM=,tag:Rk0lWqYRlA54MH+tPA+Gmw==,type:str]
    CAMERA_410_1_ADDRESS: ENC[AES256_GCM,data:PiCAnMsiP83W/9/t,iv:VK+VFnkJgKABOemfA5Mt5IK+x15tccRxV1FuXcbOWOA=,tag:6VSisRrZrje7Lu+DHhoZlw==,type:str]
    CAMERA_410_1_PASSWORD: ENC[AES256_GCM,data:pPJCpaAOdsDa2vT0wDIpag==,iv:ilAPvRZ8yYJMOjgvsJvbWtHWzBJKQVheMqoq1Lb/v0U=,tag:dh3SJiUU0ojx6f+Cqkq+bA==,type:str]
    #ENC[AES256_GCM,data:BceQ//DkU3FYkzcSACLC/R+aOgvni+mbDXE=,iv:bCUJnlXrt8Hxz0XK0tfYznJWPqHjaECfL0YS461ouN8=,tag:NWKLj9PhMWjIYA2fPhcHzw==,type:comment]
    CAMERA_410_2_PASSWORD: ENC[AES256_GCM,data:AG1WbgCfW/CtxD+mpF95Bg==,iv:v6nE7KImvTSuwQ4nb5lNkmFS4/3jNoiBWFDZ6Hj5zc8=,tag:DY4QhpKW5ukdstL/1xtkTg==,type:str]
    #ENC[AES256_GCM,data:6VcnzTeUrc39wiWhiuWOUf2J,iv:hPAoHXHTcCrl+7lCrHMKPvkkdWf/iYumIq+4q7hpMeQ=,tag:HiF2tGOdCEqfShaI/+2gOg==,type:comment]
    WALLABAG_POSTGRESQL_USERNAME: ENC[AES256_GCM,data:Ob+46FfhEH8=,iv:E9HiMIAN92QeOqhDg91ETL0WknwpsfvHXWvP/mMO6Pg=,tag:B2gHtrHnB5Ik/t6lRQIYcg==,type:str]
    WALLABAG_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:++R7/R39xWfPtDltcA09i4jXTJ3CuJmHYCFDyqZC,iv:YqkR8XCi9dgNZAR9FDrbn80Lu05qvp1s+FbB4NZxOwI=,tag:xzPQ8VZUvwWm74y7Wpc7kg==,type:str]
    WALLABAG_SECRET: ENC[AES256_GCM,data:HWdKUxWueHGXzZ9cgsgAdg7Z/ifIMPZYhlfmmXuF0e/3ulNzdRG6F6MWWuq0Sge16BU=,iv:BGbxs4Z2dI6gNc8+Oaz6/1FrkVMybNhSBvgfKaN9hOQ=,tag:KUSgadrbgOkwIB4sXYu8rg==,type:str]
    #ENC[AES256_GCM,data:iZvSIN705pUStA==,iv:H8maYfM2wfTADnRUI0YoOMN5OtSXtBTl3jTzHHB4T94=,tag:1pBooaMXoHLDAzpAuxXVgw==,type:comment]
    DRONE_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:7wRHo4tvt4Yi4apqRgxhDUTvQEzJOrAovOaJen8XvxXcpjhirs8QCvP1bUdiOy8=,iv:OygtwQK9se8fifq2lnkmZ59CBxGOv4FGN4YEoRPnPZs=,tag:qMqQebkmaIEomAp0NTGMwA==,type:str]
    DRONE_GITEA_CLIENT_ID: ENC[AES256_GCM,data:YG91836Kksr9sQ48l4PVHDHvLmkyaP5GnJt16ZwgLxX6YM3g,iv:isX5fA+EZuoBQNUHW2O68xjs4YZ/9S2pVx5I2WP13ts=,tag:u8PsM8IHlMbZxUIp77zVEg==,type:str]
    DRONE_GITEA_CLIENT_SECRET: ENC[AES256_GCM,data:/q+IPHX+uUCq8zwvi/X4AJgsigqczlH3J44T6AzR9Q55GdpSDpOF9q+OdKI=,iv:kr1uJS588WMfsMmnydaiCsjLMK2qMEpJe4rPrZVg/+U=,tag:ayQ8WxaEx4tzsDw+fiSW3w==,type:str]
    DRONE_PLUGIN_SECRET: ENC[AES256_GCM,data:fGoY7NEkrP9DnZfWfMZdKTEbWgww9ITq9+c+aG8BVHPaxINPxxxGWWU8esM=,iv:IeBmnQ5YJhBZAV6uMoXbiNcGn3P1v4XKmC1w0r7f+jk=,tag:tEwwHVHz2Lo9tXaZE6Ej2g==,type:str]
    DRONE_RPC_SECRET: ENC[AES256_GCM,data:O7vIDS3udYhNoSgMjJfzyv9WriXpVrDNIrlzkMi0ahEoA6BCBmnFHWqJp6M=,iv:zAi3NBL2drQSHVaIZHqLzAO8bO84FsU/IVSOzJNG5aw=,tag:FojMmRGpKkrGN2Ow3Tzu3Q==,type:str]
    #ENC[AES256_GCM,data:8i58L6DCx5IHEsI=,iv:vFbqRQplYGZ42jqCG8G46GBpB1uzrNXOOIcT+sLHmeo=,tag:6909nJcsxgsZoycbmk1edg==,type:comment]
    HARBOR_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:z/jtkVViLWkXleHWEfGOiPAmamfZPwDr+LxfmkVY9h/eAkMzK3k=,iv:GltPHJCBihdWZ+FeeueSr7LBrt3eJxRXYrISdqQ3IN8=,tag:lrGbNaVHCc438FU7ot0/ew==,type:str]
    #ENC[AES256_GCM,data:0UQFOiwDQ/qOHQ==,iv:tI7/xvAh2iSZLC4x1tdoyWdeDwsmuR1M9IAxa1bphng=,tag:7dZWsjrhZYhYItJEbOCZmA==,type:comment]
    GITEA_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:vG99EKvxSkU92wXUjgMgZc0eaGaqHBtzim0C78Pe9fBi48T8hgI=,iv:wMkS9lgxAlGSGDP8yjO0C1jiGsia4bnQdA6j32c4fYU=,tag:fPI2YhZkJGBZCAJ/WenhsQ==,type:str]
    #ENC[AES256_GCM,data:pKDXFI8llJiqljxSBs8=,iv:Ocvn7e/rieSJr712MSI9UMR+0sfoHFs154rCukBaSUA=,tag:d4WYOFCZmpjXeT5lQmZClw==,type:comment]
    SONARQUBE_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:uJUSTnNdjyUgxPcjHjFc+FAvE6BzFn0Vy1HV2ZNOXOXbt8j4pOFPwQ==,iv:f+wMNLmImWvwQFZtXTU+AKYbs7H6IFisSXzjHCblcpA=,tag:P9LOBk8NW7vofVLcfbdtnw==,type:str]
    #ENC[AES256_GCM,data:aSjF/DF4h1f95kY=,iv:JJLKitAZ4R9tsDK4ZsTXtqfg2tZnhtnwLOeIrUDT+Fo=,tag:63BeY4obiMyqsJMLxPUbhQ==,type:comment]
    PLEX_CLAIM_TOKEN: ENC[AES256_GCM,data:3yvi0+s40oRxslGJDC0Uw62kl3/vVCTpXGo=,iv:fpu05ZU+s8IvtyF/utsIjTcUDNehlG84MEgTbo3G19k=,tag:lcvTwtOEelREjaYFMPniMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-02-02T04:25:53Z"
    mac: ENC[AES256_GCM,data:NZ3t/+B9dSgfwTo+fjyKYhlTj10L0iotHUGml7n4FWyYpEmFtFt6ubMJa4ZrgfHzGLm+rVlUEamzgBCxiYhHDnJrNSnpiDC3x+YeohYSxzcXrCHnPp/VjdtyXVpJDNTnusRaMOzLICaTTPIOePS28BA7BywQyzkqpfrEQbRjTX8=,iv:iU99poMWUP/AhCaD12PdoF+MaHHRjl/uH/js6XRATT4=,tag:ZJweWj+jcuCaiQ7WqIBvhw==,type:str]
    pgp:
        - created_at: "2022-02-02T04:25:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DiZ7E0TI8O2gSAQdAXfhXnMoZRztMCet5fyqZY4mHK1MF4OyRfGKKSznDvwAw
            h/wcPvUJobzVn0Zb1Dftl8mfWpdFUFMHyIjqRwQvFfnlPuncf9P6K+Hh2OSkS2w/
            0l4BodrFRgFfRu3su9nPhyfyS61s/2iyWyMAJdYWl/bDyRtIK++tEl/JS3DHUTrW
            GzQnabF6qjVkPqGqvY3tbo9G8OpdxYdQBA6D8bf4Rr7DBrHzcvNq7lwnpAtn5OyZ
            =ANyN
            -----END PGP MESSAGE-----
          fp: "0x4B9C178B49228EFD"
        - created_at: "2022-02-02T04:25:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3xGBpO+04gOARAAig6jQfS5NYGTR1o7ORbr4/wKUATB9jo5fsUwLySw8Doa
            N3BeRSLxLr9nrs4TttmQCgDQY1g+PIRJcSBtA7FCcLnh9WxXgyDZejCw81nn6yBa
            YvlJ32kzU3IRIvBppXEMpQVLC9Qr9KQ3aYHYkgiqZsbHTsKzMujdmF8J1YPQFmSR
            0dO4btWMZZ3RbYxf33XGQEW/w7JRvV4tGMQgheH6RC+t0EMpob/WMJXm0Re1jccc
            hcYEhDBL2koowB6FZoUhGOYNmKM6WtF7upqMPaxyuI5jQa97o97A+aTcL9Z7Uqdm
            IEcw/4LDAOZ0l33eQ2EtGrtc/0jVP/u/9EpoTmxE0LVh7pFhJ3qCZxnMSME4JRoC
            qucpvTawlgM8vcykbUgF7DtErcxcWbi6fZ3yKDyeFMgaYjsEhIdWtFeGRV9t1tYS
            YzpL5rBSueyHvYhPm+nr6lbK2mfkJm4sZzrMm/2G93TRas7OJIuwpOJelpwvURLU
            TwfTuPnSIgyQM/m2DvOSeL3pJVRY0rQawHDvRhhM2V+rlf7yp8BomL5jjsMaSBsI
            7IhwoZ+5knRnzQUQy/QGlB1DoBRbn1CSC9xK1sMxE4t745pyxbTKYeJa3d382n9y
            fNPn7R1/qUb7dowThoamwSOcovcIhXACkLKG91dTOBBrAwIR3o0YrqyuzAAQWMTS
            XgGzkx//8SfrHwOkJhTuoV6ogYR3vINm2/MQjuh8nb+xiRJupHHoRzp9cmQxr4cF
            8hpF4/VxntwEwr86G2RQL8lbydfN+ZI8xWqpHMUM47T7RuWV2nxfTGWiODnrI/0=
            =RMEG
            -----END PGP MESSAGE-----
          fp: "0x47262D3D407ED16F"
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
