---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-operators
  namespace: flux-system
spec:
  dependsOn:
  - name: cluster-namespaces
  interval: 10m0s
  path: ./cluster/operators
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
