---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
