# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-auth
stringData:
    username: ENC[AES256_GCM,data:hKZD/dpWL08=,iv:5AFlip1wJ1kJksSMYwCwmNvk4rV02b7XlRCO8q70bDY=,tag:93i48/BKXRqnKzB4dNnODg==,type:str]
    password: ENC[AES256_GCM,data:jpQXCduh1wbYHLGJPhfLkprkNKbpJg==,iv:UKrrB7MBLE3+Q9bvwEU1T8lUR2NLaqpnbKDeTsi04BI=,tag:LjK4dhYVghhZm5ZzF2+gAQ==,type:str]
    datasource: ENC[AES256_GCM,data:GOGrd3fE0CtKX/xJSVZx011fTSDexM3EsP3h9TzDK3IlyHnVDX+ESBXx7pjJYwZi95FqIbkRDmV1qcTLVzle7tN8W/dG3b41ks9x4M4xGxToxCAy+RQ=,iv:Ix2pvkUj28uZFJXVvx5rqVTFDNAeuLx4ccPOX+nlEeQ=,tag:JLRGKEhTqMOcv3QF3fZaZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-20T15:28:06Z"
    mac: ENC[AES256_GCM,data:bslt/yuLj2/W59fsT5I7BPYTxJSXl7RpEnjhTTCHO8rjwaDFyEbxqrzzgYQVDCBIm5B+JgGuYqQJdkNfm2eYp/dFnoM3KHzvC7fqRnwqmWVtj0fQqoavhE1K83w6UvEd7hbmjnNxLjusC3LWKtcTp5EvcDt1B6gOxPKz8S0unUg=,iv:U91YSuiJy9iDA4QvRKfrKVCI1USwTPcJLWq5nygKGRQ=,tag:sZoXO3ex9ZNDj5C+qBqeXw==,type:str]
    pgp:
        - created_at: "2021-05-20T15:28:05Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DiZ7E0TI8O2gSAQdAXvlB6sn1lpuGU0fwwGeWxf4FNOLCwEMr/pVhxvt0gi8w
            xGO+MaPeFmCzs/4k1hJbAWc8vqL7yk1Bqt2tXNcReVJtLr/J2M9v62wueiU4DaFD
            0lwB45iBNXF+PF14WCTIbGb8odL1ypurKYLGN5Q1RD5hBpQ/A54o8WIYRB4w+dsN
            Tm8EDFE5m4ZEeM/+MCeBP9O8FmXW2C+wmH/6Yp9GOFehXHpwQK41838S8+JJXg==
            =MtaE
            -----END PGP MESSAGE-----
          fp: "0x4B9C178B49228EFD"
        - created_at: "2021-05-20T15:28:05Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3xGBpO+04gOAQ//StCBXUerKt4EzVafeJMwcafLr6gReNqpnnm8UB1YPL+Z
            h8VBsAGTQ1DAjluEGUmEG7FFRfl6QznwD+cQuw3NUhEbf2yFuLciUpb5o7R2ynAg
            tfIu5X3MJc707X4aRbX0aOnsxfaA7mbdi4//rbCUPMyKTpnzT635jG69n+/1PMFv
            zZ46M49GU/FwWYzLBKbx5qmM1jMl7PqU2zMX7xiaIevKsA37gs879RaLjjcYtNlc
            GobhJXD+6/AWU/6zDdnRmZO1aFEwm13aai5Y/BULTeeaMMLszMXswbb99y6sLBAL
            UcAxKyCD2D58BpIvgNH66OWL02NMWxUUyDMbrss9Jue6dyIwPJR5KErocDJDFqCs
            1qK8T1cIIxp3iC6h+FKOrpdyzyMmsQowOZ5GaLoQLBS/BzXNCTpCKWApOKatITTT
            qjRRTCZ9Ig28B7ersDWY/wJwv7CT/8iJFQuNEqTkwRWZc7bfsNycIPmmCx3wix8D
            JFwUl+7dIy8TTAld+sIL4BqqAptazkUkLmmE+4R1l2cJXKqsapBXUA2FkoqA1IcY
            ZFSjaOw3LSiJ0Hbv5CvYNaldJT3wUFFbV94kcUIhV48XthcYnIL5/+dPDBSrfJYt
            Iky9e5Cb4td+knmkk9uP+frBBkwWKDhwNWabNgni5bJMygHUa7HbWzdzyJTZxAzS
            XAH/v8rmkXU4tS6zPAdxzyv5n0Nzb+w9XzzWDCM/J+wvYZ11i6mybaw32XyxHzQS
            FJ9QhZ1aHrf8y6R+hwuV2xJCBynQ2qK1OUMo/px0q48rwnaLLhTU0atW5S/w
            =y+ol
            -----END PGP MESSAGE-----
          fp: "0x47262D3D407ED16F"
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
