apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://charts.bitnami.com/bitnami
      chart: postgresql
      version: 10.5.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    fullnameOverride: postgresql
    postgresqlPassword: ${DRONE_POSTGRESQL_PASSWORD}
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 13.3.0
      pullPolicy: IfNotPresent
    primary:
      annotations:
        kanister.kasten.io/blueprint: bitnami-postgresql
    persistence:
      enabled: true
