apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://charts.drone.io
      chart: drone
      version: 0.1.7
      sourceRef:
        kind: HelmRepository
        name: drone
        namespace: flux-system
  values:
    image:
      repository: drone/drone
      tag: 2.0.0
    persistentVolume:
      enabled: false
    ingress:
      enabled: true
      hosts:
      - host: drone.zro.io
        paths:
        - "/"
    env:
      DRONE_DATABASE_DRIVER: postgres
      DRONE_GIT_ALWAYS_AUTH: true
      DRONE_GITEA_CLIENT_ID: ${DRONE_GITEA_CLIENT_ID}
      DRONE_GITEA_CLIENT_SECRET: ${DRONE_GITEA_CLIENT_SECRET}
      DRONE_GITEA_SERVER: https://git.zro.io
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_SERVER_HOST: drone.zro.io
      DRONE_SERVER_PROTO: https
      DRONE_SERVER_PROXY_HOST: drone.drone.svc
      DRONE_SERVER_PROXY_PROTO: http
      DRONE_USER_CREATE: username:context,admin:true

  valuesFrom:
  - kind: Secret
    name: postgres-auth
    valuesKey: datasource
    targetPath: env.DRONE_DATABASE_DATASOURCE
