---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sonarr
  namespace: media
spec:
  hosts:
  - sonarr.${CLUSTER_DOMAIN}
  gateways:
  - system-ingress/gateway
  http:
  - route:
    - destination:
        host: sonarr.media.svc.cluster.local
        port:
          number: 8989
