apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClass: false
      defaultClassReplicaCount: 2
      reclaimPolicy: Retain
    csi:
      kubeletRootDir: /var/lib/kubelet
    defaultSettings:
      backupstorePollInterval: 1800
      backupTarget: s3://inwin-backups@us-west-000/longhorn
      backupTargetCredentialSecret: backup-credentials
      storageMinimalAvailablePercentage: 10
    ingress:
      enabled: true
      host: longhorn.inwin-cluster.zro.io
      annotations:
        nginx.ingress.kubernetes.io/auth-url: "https://auth.zro.io/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://auth.zro.io/oauth2/start"
