---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 100Gi

  storageClassName: rook-ceph-block
