---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-data
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 200Gi

  storageClassName: rook-ceph-block
