apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://helm.goharbor.io
      chart: harbor
      version: 1.6.2
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  values:
    expose:
      tls:
        certSource: none
      ingress:
        hosts:
          core: r.zro.io
          notary: notary.zro.io
    externalURL: https://r.zro.io
    persistence:
      imageChartStorage:
        disableredirect: true
        type: s3
        s3:
          secure: false
          bucket: harbor-registry
    database:
      type: external
      external:
        host: postgresql.registry.svc
        username: postgres
        password: ${HARBOR_POSTGRESQL_PASSWORD}
    redis:
      type: external
      external:
        addr: "redis-master.harbor.svc:6379"
    jobservice:
      jobLoggers:
      - database
  valuesFrom:
  - kind: ConfigMap
    name: harbor-bucket
    valuesKey: BUCKET_HOST
    targetPath: persistence.imageChartStorage.s3.regionendpoint
  - kind: ConfigMap
    name: harbor-bucket
    valuesKey: BUCKET_NAME
    targetPath: persistence.imageChartStorage.s3.bucket
  - kind: Secret
    name: harbor-bucket
    valuesKey: AWS_ACCESS_KEY_ID
    targetPath: persistence.imageChartStorage.s3.accesskey
  - kind: Secret
    name: harbor-bucket
    valuesKey: AWS_SECRET_ACCESS_KEY
    targetPath: persistence.imageChartStorage.s3.secretkey
