---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: harbor-ingress-notary
  namespace: harbor
spec:
  hosts:
  - notary.${CLUSTER_DOMAIN}
  gateways:
  - system-ingress/gateway
  http:
  - route:
    - destination:
        host: harbor-notary-server.harbor.svc.cluster.local
        port:
          number: 4443
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: harbor-ingress
  namespace: harbor
spec:
  hosts:
  - r.${CLUSTER_DOMAIN}
  gateways:
  - system-ingress/gateway
  http:
  - route:
    - destination:
        host: harbor-portal.harbor.svc.cluster.local
        port:
          number: 80
