apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./drone-secrets/minio.yaml
- ./drone-secrets/registry.yaml
- ./drone-secrets/sonarqube.yaml
- ./registry/harbor-values.yaml
