apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-node-exporter
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://prometheus-community.github.io/helm-charts
      chart: prometheus-node-exporter
      version: 1.18.2
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    image:
      repository: quay.io/prometheus/node-exporter
      tag: v1.1.2
      pullPolicy: IfNotPresent

    hostNetwork: false

    prometheus:
      monitor:
        enabled: true
