apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
data:
  values.yaml: |
    config: |
      mqtt:
        host: vernemq.home-assistant
        user: ${FRIGATE_MQTT_USERNAME}
        password: ${FRIGATE_MQTT_PASSWORD}
      clips:
        max_seconds: 300
        retain:
          default: 10
          objects:
            person: 60
      objects:
        track:
        - person
        - bicycle
        - car
        - motorcycle
        - bus
        - cat
        - dog
      detectors:
        cpu1:
          type: cpu
      cameras:
        garage:
          ffmpeg:
            inputs:
            - path: rtsp://neolink.media.svc:8554/garage/subStream
              roles:
              - detect
              - rtmp
              - record
            - path: rtsp://neolink.media.svc:8554/garage/mainStream
              roles:
              - clips
          width: 704
          height: 480
          fps: 6
          clips:
            enabled: True
          record:
            enabled: True
            retain_days: 15
