apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
data:
  values.yaml: |
    config: |
      mqtt:
        host: vernemq.home-assistant
        user: ${FRIGATE_MQTT_USERNAME}
        password: ${FRIGATE_MQTT_PASSWORD}
      detectors:
        cpu1:
          type: cpu
      database:
        path: /media/frigate/frigate.db
      objects:
        track:
        - person
        - bicycle
        - car
        - motorcycle
        - bus
        - cat
        - dog
      timestamp_style:
        format: "%Y-%m-%d %H:%M:%S"
      record:
        enabled: True
        retain_days: 30
        events:
          retain:
            default: 365
      cameras:
        garage:
          detect:
            height: 480
            width: 708
            fps: 6
          ffmpeg:
            inputs:
            - path: rtsp://neolink.media.svc:8554/garage/subStream
              roles:
              - detect
              - rtmp
            - path: rtsp://neolink.media.svc:8554/garage/mainStream
              roles:
              - record
