apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
spec:
  interval: 1h
  chart:
    spec:
      chart: charts/frigate
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image:
      repository: blakeblackshear/frigate
      tag: 0.8.4-amd64
    timezone: 'America/Chicago'
    rtspPassword: ${FRIGATE_RTSP_PASSWORD}
    extraVolumes:
    - name: media
      persistentVolumeClaim:
        claimName: nvr-pool
    - name: cache
      emptyDir:
        medium: Memory
    extraVolumeMounts:
    - name: media
      mountPath: /media/frigate
    - name: cache
      mountPath: /tmp/cache
  valuesFrom:
  - kind: ConfigMap
    name: frigate-config
