---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frigate
  namespace: media
spec:
  hosts:
  - frigate.${CLUSTER_DOMAIN}
  gateways:
  - system-ingress/gateway
  http:
  - route:
    - destination:
        host: authentik.system-ingress.svc.cluster.local
        port:
          number: 80
