---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwave2mqtt-config
  namespace: home-assistant
spec:
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 8Gi

  storageClassName: rook-ceph-block
