apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://k8s-at-home.com/charts/
      chart: oauth2-proxy
      version: 5.0.7
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: quay.io/oauth2-proxy/oauth2-proxy
      tag: v7.2.1
    replicaCount: 2
    extraArgs:
      provider: "github"
      provider-display-name: "Gitea"
      login-url: "https://git.${CLUSTER_DOMAIN}/login/oauth/authorize"
      redeem-url: "https://git.${CLUSTER_DOMAIN}/login/oauth/access_token"
      validate-url: "https://git.${CLUSTER_DOMAIN}/api/v1/user"
    config:
      cookieSecret: ${OAUTH_COOKIE_SECRET}
      clientID: ${OAUTH_CLIENT_ID}
      clientSecret: ${OAUTH_CLIENT_SECRET}
      configFile: |
        auth_logging = true
        cookie_domains = ".${CLUSTER_DOMAIN}"
        cookie_httponly = true
        cookie_name = "_inwin_oauth"
        cookie_refresh = "1h"
        cookie_samesite = "lax"
        cookie_secure = true
        email_domains = [ "*" ]
        pass_access_token = true
        pass_authorization_header = true
        pass_host_header = true
        redirect_url = "https://auth.${CLUSTER_DOMAIN}/oauth2/callback"
        request_logging = true
        session_store_type = "cookie"
        set_authorization_header = true
        set_xauthrequest = true
        silence_ping_logging = true
        skip_auth_strip_headers = false
        skip_jwt_bearer_tokens = false
        skip_provider_button = true
        standard_logging = true
        upstreams = [ "static://200" ]
        whitelist_domains = ".${CLUSTER_DOMAIN}"
