---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: oauth2-proxy
  namespace: system-ingress
spec:
  hosts:
  - auth.${CLUSTER_DOMAIN}
  gateways:
  - system-ingress/gateway
  http:
  - route:
    - destination:
        host: oauth2-proxy.system-ingress.svc.cluster.local
        port:
          number: 80
