apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
data:
  values.yaml: |
    config: |
      mqtt:
        host: vernemq.home-assistant
        user: ${FRIGATE_MQTT_USERNAME}
        password: ${FRIGATE_MQTT_PASSWORD}
      clips:
        max_seconds: 300
        retain:
          default: 10
          objects:
            person: 60
      objects:
        track:
        - person
        - bicycle
        - car
        - motorcycle
        - bus
        - cat
        - dog
      detectors:
        cpu1:
          type: cpu
      cameras:
        # front:
        #   ffmpeg:
        #     inputs:
        #     - path: rtsp://frigate:${CAMERA_410_1_PASSWORD}@${CAMERA_410_1_ADDRESS}//h264Preview_01_sub
        #       roles:
        #       - detect
        #       - rtmp
        #       - record
        #     - path: rtsp://frigate:${CAMERA_410_1_PASSWORD}@${CAMERA_410_1_ADDRESS}//h264Preview_01_main
        #       roles:
        #       - clips
        #   width: 640
        #   height: 480
        #   fps: 7
        #   clips:
        #     enabled: True
        #   record:
        #     enabled: True
        #     retain_days: 30
        garage:
          ffmpeg:
            inputs:
            - path: rtsp://neolink.neolink.svc:8554/garage/subStream
              roles:
              - detect
              - rtmp
              - record
            - path: rtsp://neolink.neolink.svc:8554/garage/mainStream
              roles:
              - clips
          width: 704
          height: 480
          fps: 6
          clips:
            enabled: True
          record:
            enabled: True
            retain_days: 15
