apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 12.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: k8sathome/radarr
      tag: v3.0.2.4552
    env:
      TZ: "America/Chicago"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${CLUSTER_DOMAIN}/oauth2/start
          nginx.ingress.kubernetes.io/auth-url: https://auth.${CLUSTER_DOMAIN}/oauth2/auth
        hosts:
        - host: radarr.${CLUSTER_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
      api:
        enabled: true
        nameSuffix: "api"
        hosts:
        - host: radarr.${CLUSTER_DOMAIN}
          paths:
          - path: /api
            pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
      media:
        enabled: true
        type: pvc
        existingClaim: media-pool
        mountPath: /media
    resources:
      requests:
        memory: 250Mi
        cpu: 250m
      limits:
        memory: 1500Mi
