apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics-operator
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://victoriametrics.github.io/helm-charts/
      chart: victoria-metrics-operator
      version: 0.1.15
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
  values:
    image:
      repository: victoriametrics/operator
      tag: v0.15.1
      pullPolicy: IfNotPresent

    createCRD: true

    operator:
      disable_prometheus_converter: false
      enable_converter_ownership: true

    resources:
      limits:
        cpu: 500m
        memory: 1Gi
