apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-state-metrics
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://prometheus-community.github.io/helm-charts
      chart: kube-state-metrics
      version: 6.13.2
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    image:
      repository: k8s.gcr.io/kube-state-metrics/kube-state-metrics
      tag: v2.0.0
      pullPolicy: IfNotPresent

    prometheus:
      monitor:
        enabled: true
