apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
spec:
  interval: 1h
  chart:
    spec:
      chart: charts/linogics-n8n
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    image:
      repository: n8nio/n8n
      tag: 0.164.1

    env:
      TZ: America/Chicago
      N8N_PORT: "5678"
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      QUEUE_BULL_REDIS_HOST: redis-master

      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: postgres
      DB_POSTGRESDB_HOST: postgresql
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: ${N8N_POSTGRESQL_PASSWORD}
      DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED: "false"

    persistence:
      enabled: true
      existingClaim: n8n-data
