apiVersion: v1
kind: Pod
metadata:
  name: volview
spec:
  containers:
  - name: volview
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
    - sleep
    - "3600"
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volume
      mountPath: /data
  restartPolicy: Always
  volumes:
  - name: volume
    persistentVolumeClaim:
      claimName: zwave2mqtt-config
