---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: triliovault-operator
  namespace: flux-system
spec:
  interval: 30m0s
  url: http://charts.k8strilio.net/trilio-stable/k8s-triliovault-operator
  timeout: 3m
