apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://grafana.github.io/loki/charts/
      chart: loki-stack
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: flux-system
  values:
    loki:
      persistence:
        enabled: true
        size: 100Gi
    promtail:
      extraScrapeConfigs:
      - job_name: syslog
        syslog:
          listen_address: 0.0.0.0:514
          labels:
            job: syslog
      syslogService:
        enabled: true
