apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  interval: 1h
  chart:
    spec:
      # registryUrl=https://k8s-at-home.com/charts/
      chart: vaultwarden
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: vaultwarden/server
      tag: 1.21.0
    env:
      TZ: "America/Chicago"
    persistence:
      config:
        enabled: true
        existingClaim: bitwarden-data
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
        - host: warden.${CLUSTER_DOMAIN}
          paths:
          - path: "/"
            pathType: Prefix
