---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bitwarden.yaml
- blocky.yaml
- dashboard.yaml
- drone.yaml
- flux-system.yaml
- gitea.yaml
- home-assistant.yaml
- kube-system.yaml
- longhorn-system.yaml
- media.yaml
- minio.yaml
- neolink.yaml
- nextcloud.yaml
- oauth2-proxy.yaml
- registry.yaml
- sonarqube.yaml
- system-ingress.yaml
- system-kasten.yaml
- system-kubedb.yaml
- system-monitor.yaml
- system-rook-ceph.yaml
- unifi.yaml
- wallabag.yaml
